In [1]:
import requests
from bs4 import BeautifulSoup
import pprint
import time

movie_name = []
movie_year = []
movie_rating = []
lst = [1,51,101,151,201,251]

for i in lst:
    #url2 = "https://www.imdb.com/search/title/?title_type=tv_movie&release_date=2000-01-01,2000-12-30&sort=num_votes,desc&start="+ str(i) +"&ref_=adv_nxt"
    url = ("https://www.imdb.com/search/title/?title_type=tv_movie&release_date=2000-01-01,2000-12-30&sort=num_votes,desc&start={}&ref_=adv_nxt".format(i))
    response = requests.get(url)
    time.sleep(5)
    content = response.content
    soup = BeautifulSoup(content, 'html.parser')
    liste_films = soup.find_all(class_="lister-list")
    
    #print(liste_films)

    liste_films = liste_films[0]

    #print(liste_films[0])
    
    films = liste_films.find_all("h3")

    for i in films:
        #print(i)
        #print("---")
        nomfilm = i.find("a").text
        movie_name.append(nomfilm)
        anneefilm = i.find(class_="lister-item-year text-muted unbold").text
        movie_year.append(anneefilm)

    films = liste_films.find_all(class_="ratings-bar")

    for i in films:
        ratingfilm = i.find("div")
        ratingfilm = ratingfilm["data-value"]
        movie_rating.append(ratingfilm)
    
import pandas as pd

df = pd.DataFrame({"Film" : movie_name,
                   "Année" : movie_year,
                   "Rating" : movie_rating})
df

                                                  Film            Année Rating
0                         Paradise Lost 2: Revelations  (2000 TV Movie)    7.6
1                                      Sex révélations  (2000 TV Movie)    7.1
2                                         Point limite  (2000 TV Movie)    7.3
3                           Juste une question d'amour  (2000 TV Movie)    7.7
4                                         On the Beach  (2000 TV Movie)      7
..                                                 ...              ...    ...
295              Gladiator Games: The Roman Bloodsport  (2000 TV Movie)    6.5
296                                         Seeing Red  (2000 TV Movie)    8.3
297  Hooked: Illegal Drugs & How They Got That Way ...  (2000 TV Movie)    7.5
298                                            Mustang  (2000 TV Movie)    5.4
299                                        Never Never  (2000 TV Movie)    7.8

[300 rows x 3 columns]